DA_CNW_BarberShop/DA_CNW_BarberShop/Controllers/DichVuController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DA_CNW_BarberShop.Models;

namespace DA_CNW_BarberShop.Controllers
{
    public class DichVuController : Controller
    {
        // GET: DichVu
        DBBarberShopDataContext db = new DBBarberShopDataContext();
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult loadDichVu()
        {
            var query = db.tblServices.Take(4).ToList();
            return View(query);
        }
    }
}

DA_CNW_BarberShop/DA_CNW_BarberShop/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DA_CNW_BarberShop.Models;

namespace DA_CNW_BarberShop.Controllers
{
    public class HomeController : Controller
    {
        DBBarberShopDataContext db = new DBBarberShopDataContext();
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
        public ActionResult DangNhap()
        {
            return View();
        }
        [HttpPost]
        public ActionResult DangNhap(TaiKhoan tk)
        {
            try
            {
                //var query = from kh in db.tblCustomers
                //            where kh.sPhoneNumber == tk.UserName
                //            where kh.sPassword == tk.Password
                //            select new TaiKhoan { UserName = kh.sPhoneNumber,
                //                Password = kh.sPassword };
                var query = db.tblCustomers.Where(kh => kh.sPhoneNumber == tk.UserName).FirstOrDefault();
                if(query != null)
                {
                    Session["DangNhap"] = query.sNameCustomer;
                    if(Session["isXemChiTiet"] != null)
                    {
                        return RedirectToAction("XemChiTietSanPham", "SanPham", new { @MaSP = Session["isXemChiTiet"] });
                    }
                    else
                    {
                        return RedirectToAction("DanhSachSanPham", "SanPham");

                    }
                }
                else
                {
                    Session["DangNhap"] = null;
                    ViewBag.DangNhapError = "Sai tài khoản hoặc mật khẩu";
                }
            }
            catch(Exception)
            {
                Session["DangNhap"] = null;
                ViewBag.DangNhapError = "Sai tài khoản hoặc mật khẩu";
            }
            return View();
        }
        public ActionResult TimKiem(string strSearch)
        {
            if(Session["DangNhap"] != null)
            {
                Session["DangNhap"] = Session["DangNhap"];
            }
            var query = from sanPham in db.tblProducts
                        join giamGia in db.tblDiscounts
                        on sanPham.FK_sDiscountID equals giamGia.PK_sDiscountID
                        where sanPham.sProductName.Contains(strSearch)
                        orderby giamGia.fRatioDiscount descending
                        select new TTSanPham
                        {
                            SanPhamID = sanPham.PK_iProductID,
                            TenSanPham = sanPham.sProductName,
                            MoTaSanPham = sanPham.sDescription,
                            GiaSanPham = Convert.ToDouble(sanPham.fPrice),
                            HinhAnh = sanPham.sImage,
                            SoLuongSPTon = Convert.ToInt32(sanPham.iQuantityInStock),
                            SoLuongXem = Convert.ToInt32(sanPham.iViewNumber),
                            SoSaoDanhGiaSP = Convert.ToInt32(sanPham.sStar),
                            LoaiGiamGia = giamGia.PK_sDiscountID,
                            TiLeGiamGia = giamGia.fRatioDiscount,
                            LoaiSanPham = sanPham.FK_sCategoryProductID
                        };
            return View(query.ToList());

        }
    }
}

DA_CNW_BarberShop/DA_CNW_BarberShop/Controllers/SanPhamController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DA_CNW_BarberShop.Models;
using PagedList;
using PagedList.Mvc;

namespace DA_CNW_BarberShop.Controllers
{
    public class SanPhamController : Controller
    {
        // GET: SanPham
        DBBarberShopDataContext db = new DBBarberShopDataContext();
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult loadSanPhamCoGiamGia()
        {
            var query = from sanPham in db.tblProducts
                        join giamGia in db.tblDiscounts
                        on sanPham.FK_sDiscountID equals giamGia.PK_sDiscountID
                        orderby giamGia.fRatioDiscount descending
                        select new TTSanPham
                        {
                            SanPhamID = sanPham.PK_iProductID,
                            TenSanPham = sanPham.sProductName,
                            MoTaSanPham = sanPham.sDescription,
                            GiaSanPham = Convert.ToDouble(sanPham.fPrice),
                            HinhAnh = sanPham.sImage,
                            SoLuongSPTon = Convert.ToInt32(sanPham.iQuantityInStock),
                            SoLuongXem = Convert.ToInt32(sanPham.iViewNumber),
                            SoSaoDanhGiaSP = Convert.ToInt32(sanPham.sStar),
                            LoaiGiamGia = giamGia.PK_sDiscountID,
                            TiLeGiamGia = giamGia.fRatioDiscount,
                            LoaiSanPham = sanPham.FK_sCategoryProductID
                        };
            return View(query.Take(4).ToList());
        }
        public ActionResult XemChiTietSanPham(int MaSP)
        {
            if (Session["DangNhap"] != null)
                Session["DangNhap"] = Session["DangNhap"];
            var query = from sanPham in db.tblProducts
                        join giamGia in db.tblDiscounts
                        on sanPham.FK_sDiscountID equals giamGia.PK_sDiscountID
                        where sanPham.PK_iProductID == MaSP
                        select new TTSanPham
                        {
                            SanPhamID = sanPham.PK_iProductID,
                            TenSanPham = sanPham.sProductName,
                            MoTaSanPham = sanPham.sDescription,
                            GiaSanPham = Convert.ToDouble(sanPham.fPrice),
                            HinhAnh = sanPham.sImage,
                            SoLuongSPTon = Convert.ToInt32(sanPham.iQuantityInStock),
                            SoLuongXem = Convert.ToInt32(sanPham.iViewNumber),
                            SoSaoDanhGiaSP = Convert.ToInt32(sanPham.sStar),
                            LoaiGiamGia = giamGia.PK_sDiscountID,
                            TiLeGiamGia = giamGia.fRatioDiscount,
                            LoaiSanPham = sanPham.FK_sCategoryProductID
                        };
            return View(query.ToList());
        }
        public ActionResult DanhSachSanPham( int ? i)
        {

            if(Session["DangNhap"] != null)
            {
                Session["DangNhap"] = Session["DangNhap"];
            }
            var query = from sanPham in db.tblProducts
                        join giamGia in db.tblDiscounts
                        on sanPham.FK_sDiscountID equals giamGia.PK_sDiscountID
                        orderby sanPham.PK_iProductID descending
                        select new TTSanPham
                        {
                            SanPhamID = sanPham.PK_iProductID,
                            TenSanPham = sanPham.sProductName,
                            MoTaSanPham = sanPham.sDescription,
                            GiaSanPham = Convert.ToDouble(sanPham.fPrice),
                            HinhAnh = sanPham.sImage,
                            SoLuongSPTon = Convert.ToInt32(sanPham.iQuantityInStock),
                            SoLuongXem = Convert.ToInt32(sanPham.iViewNumber),
                            SoSaoDanhGiaSP = Convert.ToInt32(sanPham.sStar),
                            LoaiGiamGia = giamGia.PK_sDiscountID,
                            TiLeGiamGia = giamGia.fRatioDiscount,
                            LoaiSanPham = sanPham.FK_sCategoryProductID
                        };
            return View(query.ToPagedList(i ?? 1, 12));
        }
        public ActionResult TenLoaiSanPham()
        {
            var query = db.tblCategoryProducts.Take(6).ToList();
            return View(query);
        }
        public ActionResult SanPhamTrongLoai(string MaLoai)
        {
            var query = from sanPham in db.tblProducts
                        join giamGia in db.tblDiscounts
                        on sanPham.FK_sDiscountID equals giamGia.PK_sDiscountID
                        where sanPham.FK_sCategoryProductID == MaLoai
                        select new TTSanPham
                        {
                            SanPhamID = sanPham.PK_iProductID,
                            TenSanPham = sanPham.sProductName,
                            MoTaSanPham = sanPham.sDescription,
                            GiaSanPham = Convert.ToDouble(sanPham.fPrice),
                            HinhAnh = sanPham.sImage,
                            SoLuongSPTon = Convert.ToInt32(sanPham.iQuantityInStock),
                            SoLuongXem = Convert.ToInt32(sanPham.iViewNumber),
                            SoSaoDanhGiaSP = Convert.ToInt32(sanPham.sStar),
                            LoaiGiamGia = giamGia.PK_sDiscountID,
                            TiLeGiamGia = giamGia.fRatioDiscount,
                            LoaiSanPham = sanPham.FK_sCategoryProductID
                        };
            return View(query.ToList());
        }
    }

}

DA_CNW_BarberShop/DA_CNW_BarberShop/Views/Home/DangNhap.cshtml
@model DA_CNW_BarberShop.Models.TaiKhoan

@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Đăng nhập</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" />
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <script src="https://cdn.rawgit.com/PascaleBeier/bootstrap-validate/v2.2.0/dist/bootstrap-validate.js"></script>
    <style>
        .gradient-custom-2 {
            /* fallback for old browsers */
            background: #fccb90;
            /* Chrome 10-25, Safari 5.1-6 */
            background: -webkit-linear-gradient(to right, #ee7724, #d8363a, #dd3675, #b44593);
            /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */
            background: linear-gradient(to right, #ee7724, #d8363a, #dd3675, #b44593);
        }
    </style>
</head>
<body>
    @using (Html.BeginForm())
    {
        <section class="h-100 gradient-form" style="background-color: #eee;">
            <div class="container py-5 h-100">
                <div class="row d-flex justify-content-center align-items-center h-100">
                    <div class="col-xl-10">
                        <div class="card rounded-3 text-black">
                            <div class="row g-0">
                                <div class="col-lg-6">
                                    <div class="card-body p-md-5 mx-md-4">

                                        <div class="text-center">
                                            <img src="~/assets/Images/log-30shine-white.9945e644.jpg" style="width: 185px;" alt="logo">
                                            <h4 class="mt-1 mb-5 pb-1">Thay đổi phong cách</h4>
                                        </div>

                                        <form>
                                            <p>Vui lòng đăng nhập để tiếp tục</p>

                                            <div class="form-outline mb-4">
                                                <input type="text" id="form2Example11" name="UserName" class="form-control" placeholder="Phone number or email address" />
                                                
                                                <label class="form-label" for="form2Example11">Tên đăng nhập</label>
                                            </div>

                                            <div class="form-outline mb-4">
                                                <input type="password" id="form2Example22" name="Password" placeholder="Password" class="form-control" />
                                                <label class="form-label" for="form2Example22">Mật khẩu</label>
                                            </div>

                                            <div class="text-center pt-1 mb-5 pb-1">
                                                <button class="btn btn-primary btn-block fa-lg gradient-custom-2 mb-3" type="submit">Đăng nhập</button>
                                                <a class="text-muted" href="#!">Quên mật khẩu?</a>
                                            </div>

                                            <div class="d-flex align-items-center justify-content-center pb-4">
                                                <p class="mb-0 me-2">Bạn chưa có tài khoản</p>
                                                @*<button type="button" class="btn btn-outline-danger">Tạo tài khoản</button>*@
                                            </div>

                                        </form>

                                    </div>
                                </div>
                                <div class="col-lg-6 d-flex align-items-center gradient-custom-2">
                                    <div class="text-white px-3 py-4 p-md-5 mx-md-4">
                                        <h4 class="mb-4">Thay đổi phong cách - Thay đổi cái nhìn</h4>
                                        <p class="small mb-0">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    }

</body>
</html>

DA_CNW_BarberShop/DA_CNW_BarberShop/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout_TrangChu.cshtml";
}
@* Banner đặt lịch *@
<div id="banner" class="banner" style="background-image: url(../../assets/Images/211001_BANNER_WEB_30SHINE_w.jpg)">
    <span class="banner-control banner-control--left" onclick="clickNextSlide()">
        <i class="banner-control__icon fa fa-angle-left" aria-hidden="true"></i>
    </span>
    <div class="banner-model">
        <div class="banner-model__heading">
            <span class="banner-model__heading--main">ĐẶT LỊCH GIỮ CHỖ CHỈ 30 GIÂY</span>
            <span class="banner-model__heading--sub">Cắt xong trả tiền, hủy lịch không sao</span>
        </div>
        @*@Html.BeginForm("showViewMain", "DatLich") {*@
        <div class="banner-model__control">
            <input type="text" id="txtInputPhone" name="sdt" class="banner-model__input" placeholder="Nhập SĐT để đặt lịch">
            <button class="banner-model__button btn" id="banner-model__btn">đặt lịch ngay</button>
            <button class="banner-model__button btn banner-model__button--mobile" id="banner-model__btn-mobile">đặt ngay</button>
        </div>
        @*}*@
    </div>
    <span class="banner-control banner-control--right" onclick="clickNextSlide()">
        <i class="banner-control__icon fa fa-angle-right" aria-hidden="true"></i>
    </span>
</div>


<div class="content">
    @* Giới thiệu dịch vụ *@
    @Html.Action("loadDichVu", "DichVu")
    @* Những câu hỏi thường gặp *@
    <div class="serve layout">
        <div class="wide grid">
            <div class="head">
                <div class="head__title">
                    <div class="head__title--main">Lắng nghe và tận tâm</div>
                    <div class="head__title--sub">Thấu hiểu nhu cầu và hổ trợ nhiệt tình</div>
                </div>
                <a href="#" class="head__view-all">
                    <span class="col c-0">Xem tất cả</span>
                    <span class="head__view-all--icon">
                        <i class="fa fa-angle-right" aria-hidden="true"></i>
                    </span>
                </a>
            </div>
            <div class="row layout-20">
                <div class="serve-content__list col l-3 m-12 c-12">
                    <div class="blog__item">
                        <div class="blog__media">
                            <img src="~/assets/Images/lang-nghe-tan-tam-1.jpg" alt="#"
                                 class="blog__media-img">
                        </div>
                        <span class="blog__text">Nói gì với stylist để có kiểu tóc ưng ý</span>
                    </div>
                </div>
                <div class="serve-content__list col l-3 m-12 c-12">
                    <div class="blog__item">
                        <div class="blog__media">
                            <img src="~/assets/Images/lang-nghe-tan-tam-3.jpg" alt="#"
                                 class="blog__media-img">
                        </div>
                        <span class="blog__text">Những câu hỏi thường gặp</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
    @* Giới thiệu hành trình tỏa sáng *@
    <div class="content-posts">
        <div class="wide grid">
            <div class="head">
                <div class="head__title">
                    <div class="head__title--main">Hành trình tỏa sáng</div>
                    <div class="head__title--sub">Câu chuyện chân thực từ hàng chục ngàn khách hàng</div>
                </div>
                <a href="#" class="head__view-all">
                    <span class="col c-0">Xem tất cả</span>
                    <span class="head__view-all--icon">
                        <i class="fa fa-angle-right" aria-hidden="true"></i>
                    </span>
                </a>
            </div>
            <div class="row post__list layout-20">
                <span class="banner-control banner-control--left" onclick="clickNextSlide()">
                    <i class="banner-control__icon fa fa-angle-left" aria-hidden="true"></i>
                </span>
                <div class="col l-6 height-100">
                    <a href="#" class="blog__item">
                        <div class="blog__media">
                            <img src="~/assets/Images/30shine-thay-doi-ngoai-hinh.jpg" alt="#"
                                 class="blog__media-img">
                        </div>
                        <span class="blog__text">Thay đổi ngoại hình, chàng trai lạnh lùng ít nói khiến cô hoa khôi rung động</span>
                    </a>
                </div>
                <div class="col l-6 height-100">
                    <a href="#" class="blog__item">
                        <div class="blog__media">
                            <img src="~/assets/Images/30shine-nam-sinh-kien-truc-lot-xac.jpg" alt="#"
                                 class="blog__media-img">
                        </div>
                        <span class="blog__text">Can đảm thay đổi mái tóc 7 năm, nam sinh thay đổi kiểu tóc mới cực đẹp</span>
                    </a>
                </div>
                <span class="banner-control banner-control--right" onclick="clickNextSlide()">
                    <i class="banner-control__icon fa fa-angle-right" aria-hidden="true"></i>
                </span>
            </div>
        </div>
    </div>

    <!-- introduce -->
    @*@Html.Action("getDataPostHomePage", "Posts")*@
    <!-- product-sale -->
    @* Những câu hỏi tư vấn *@
    <div class="content-product-sale layout">
        <div class="wide grid">
            <div class="head">
                <div class="head__title">
                    <div class="head__title--main">Ưu đãi</div>
                    <div class="head__title--sub">Quà tặng, chiết khấu được cập nhật liên tục</div>
                </div>
                <a href="#" class="head__view-all">
                    <span class="col c-0">Xem tất cả</span>
                    <span class="head__view-all--icon">
                        <i class="fa fa-angle-right" aria-hidden="true"></i>
                    </span>
                </a>
            </div>
            <div class="blog__list row layout-20">
                <span class="banner-control banner-control--left" onclick="clickNextSlide()">
                    <i class="banner-control__icon fa fa-angle-left" aria-hidden="true"></i>
                </span>
                <div class="col l-4 m-12 c-12">
                    <a href="#" class="blog__item">
                        <div class="blog__media">
                            <img src="~/assets/Images/small_ACSYS_vuong_4db7dc1695.jpg" alt="#"
                                 class="blog__media-img">
                        </div>
                        <span class="blog__text limits-text-2 blog__text-product-sale">Nói gì với stylist để có kiểu tóc ưng ý</span>
                    </a>
                </div>
                <div class="col l-4 m-12 c-12">
                    <a href="#" class="blog__item">
                        <div class="blog__media">
                            <img src="~/assets/Images/small_Mood_dep_trai_11_7298a8b45d.jpg" alt="#"
                                 class="blog__media-img">
                        </div>
                        <span class="blog__text limits-text-2 blog__text-product-sale">Nói gì với stylist để có kiểu tóc ưng ý</span>
                    </a>
                </div>
                <div class="col l-4 m-12 c-12">
                    <a href="#" class="blog__item">
                        <div class="blog__media">
                            <img src="~/assets/Images/small_Mood_dep_trai_9_ea25c333c8.jpg" alt="#"
                                 class="blog__media-img">
                        </div>
                        <span class="blog__text limits-text-2 blog__text-product-sale">Nói gì với stylist để có kiểu tóc ưng ý</span>
                    </a>
                </div>
                <span class="banner-control banner-control--right" onclick="clickNextSlide()">
                    <i class="banner-control__icon fa fa-angle-right" aria-hidden="true"></i>
                </span>
            </div>
        </div>
    </div>
    <!-- product -->
    @Html.Action("loadSanPhamCoGiamGia", "SanPham")
    @* Những dịch vụ khác *@
    <div class="content-care-custom layout">
        <div class="wide grid">
            <div class="head layout-20">
                <div class="head__title">
                    <div class="head__title--main">30shine shop</div>
                    <div class="head__title--sub">Mỹ phẩm nam cao cấp chính hãng</div>
                </div>
            </div>
            <div class="content-banner relative">
                <img src="~/assets/Images/banner-30shine-care-5.jpg"
                     alt="#" class="content-banner__img">
                <div class="banner__wrapper">
                    <div class="banner__text">
                        <div class="banner__text--main">VÌ CHẤT LƯỢNG PHỤC VỤ LÀ HÀNG ĐẦU</div>
                        <div class="banner__text--sub">Áp dụng tại salon bất kỳ toàn hệ thống 30Shine</div>
                    </div>
                </div>
            </div>

            <div class="blog__list layout-20 row">
                <div class="col l-3 m-12 c-12">
                    <a href="#" class="list__item">
                        <div class="list__item-media">
                            <img src="~/assets/Images/1-care.png"
                                 alt="" class="list__item-media-img">
                        </div>
                        <div class="list__item-text">
                            <div class="list__item-text--main">3 ngày</div>
                            <div class="list__item-text--sub">Đổi / trả hàng miễn phí</div>
                        </div>
                    </a>
                </div>
                <div class="col l-3 m-12 c-12">
                    <a href="#" class="list__item">
                        <div class="list__item-media">
                            <img src="~/assets/Images/2-care.png"
                                 alt="" class="list__item-media-img">
                        </div>
                        <div class="list__item-text">
                            <div class="list__item-text--main">7 ngày</div>
                            <div class="list__item-text--sub">Chỉnh sửa tóc miễn phí</div>
                        </div>
                    </a>
                </div>
                <div class="col l-3 m-12 c-12">
                    <a href="#" class="list__item">
                        <div class="list__item-media">
                            <img src="~/assets/Images/3-care.png"
                                 alt="" class="list__item-media-img">
                        </div>
                        <div class="list__item-text">
                            <div class="list__item-text--main">15 ngày</div>
                            <div class="list__item-text--sub">Bảo hành uốn nhuộm</div>
                        </div>
                    </a>
                </div>
                <div class="col l-3 m-12 c-12">
                    <a href="#" class="list__item">
                        <div class="list__item-media">
                            <img src="~/assets/Images/4-care.png"
                                 alt="" class="list__item-media-img">
                        </div>
                        <div class="list__item-text">
                            <div class="list__item-text--main">Giảm 20%</div>
                            <div class="list__item-text--sub">Giảm 20% nếu chờ đợi quá lâu</div>
                        </div>
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>

DA_CNW_BarberShop/DA_CNW_BarberShop/Views/Home/TimKiem.cshtml
@model List<DA_CNW_BarberShop.Models.TTSanPham>
@{
    ViewBag.Title = "TimKiem";
    Layout = "~/Views/Shared/_Layout_SanPham.cshtml";
}

<h2>Tìm kiếm sản phẩm</h2>
<div class="product-content">
    <div class="product-content__heading">
        <div class="product-content__heading-text">
            <span class="product-content__heading--main">GỢI Ý HÔM NAY MUA SẮM LIỀN TAY</span>
            <span class="product-content__heading--sub">Lựa Chọn Hàng Đầu Dành Cho Quý Khách</span>
        </div>
        <div class="wide grid">
            @Html.Action("TenLoaiSanPham", "SanPham")
        </div>
    </div>
    <div class="products">
        <div class="grid wide">
            <div class="product-list row">
                @{
                    foreach (var item in Model)
                    {
                        <div class="col l-3 m-6 c-12">
                            <a href="@Url.Action("XemChiTietSanPham", "SanPham", new {@MaSP = item.SanPhamID })" class="product-item">
                                <img src=@Url.Content("~/assets/Images/img-product/" + item.HinhAnh) alt="" class="product-item__img">
                                <span class="product-item__name">@item.TenSanPham</span>
                                <div class="product-item__price">
                                    <span class="product-item__price--main">
                                        @string.Format("{0:0,0}", @item.GiaSau) VNĐ
                                    </span>
                                    @if (item.GiaSau != item.GiaSanPham)
                                    {
                                        <span style="text-decoration-line: line-through" class="product-item__price--sub">

                                            @string.Format("{0:0,0}", @item.GiaSanPham) VNĐ
                                        </span>
                                    }
                                </div>

                                <span class="product-item__star">
                                    <i class="fa fa-star-o" aria-hidden="true"></i>
                                    <i class="fa fa-star-o" aria-hidden="true"></i>
                                    <i class="fa fa-star-o" aria-hidden="true"></i>
                                    <i class="fa fa-star-o" aria-hidden="true"></i>
                                    <i class="fa fa-star-o" aria-hidden="true"></i>
                                </span>
                                @if (@item.LoaiGiamGia != "CHUAGIAMGIA")
                                {
                                    <div class="sticker-percent">
                                        <div class="sticker-percent__text">
                                            <p>- @item.TiLeGiamGia %</p>
                                        </div>
                                    </div>
                                }
                            </a>
                        </div>
                    }
                }
            </div>
            @*<span class="pagination_text">
                Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) / @Model.PageCount
            </span>

            @Html.PagedListPager(Model, i => Url.Action("DanhSachSanPham", "SanPham", new { i, @class = "123123" }))*@
        </div>
    </div>
    @* Thương hiệu nổi bật *@
    <div class="trademark wide grid">
        <div class="trademark-heading">
            <h2>THƯƠNG HIỆU NỔI BẬT</h2>
        </div>
        <div class="row">
            <div class="col l-2 c-6 m-4">
                <div class="trademark-item">
                    <img src="~/assets/Images/banner_vendors_show_1_img.jpg" alt="">
                </div>
            </div>
            <div class="col l-2 c-6 m-4">
                <div class="trademark-item">
                    <img src="~/assets/Images/banner_vendors_show_2_img.jpg" alt="">
                </div>
            </div>
            <div class="col l-2 c-6 m-4">
                <div class="trademark-item">
                    <img src="~/assets/Images/banner_vendors_show_3_img.jpg" alt="">
                </div>
            </div>
            <div class="col l-2 c-6 m-4">
                <div class="trademark-item">
                    <img src="~/assets/Images/banner_vendors_show_4_img.jpg" alt="">
                </div>
            </div>
            <div class="col l-2 c-6 m-4">
                <div class="trademark-item">
                    <img src="~/assets/Images/banner_vendors_show_5_img.jpg" alt="">
                </div>
            </div>
            <div class="col l-2 c-6 m-4">
                <div class="trademark-item">
                    <img src="~/assets/Images/banner_vendors_show_6_img.jpg" alt="">
                </div>
            </div>

        </div>
    </div>
</div>